// Small, local reference data. No network, code generation, or compiler dependency.
const fn = (label, signature, info) => ({ label, type: 'function', detail: signature, info });
const value = (label, info, type = 'constant') => ({ label, type, info });
export const coreCompletions = [
  fn('pinMode', 'void pinMode(uint8_t pin, uint8_t mode)', 'Choose INPUT, OUTPUT, or INPUT_PULLUP for a pin.'),
  fn('digitalWrite', 'void digitalWrite(uint8_t pin, uint8_t value)', 'Set a digital output HIGH or LOW.'),
  fn('digitalRead', 'int digitalRead(uint8_t pin)', 'Read HIGH or LOW from a digital pin.'),
  fn('analogRead', 'int analogRead(uint8_t pin)', 'Read a 10-bit analog value, from 0 to 1023.'),
  fn('analogWrite', 'void analogWrite(uint8_t pin, int value)', 'Set PWM duty cycle from 0 to 255. Uno PWM pins: 3, 5, 6, 9, 10, 11.'),
  fn('analogReference', 'void analogReference(uint8_t mode)', 'Select DEFAULT, INTERNAL, or EXTERNAL analog reference. Check wiring before changing reference.'),
  fn('delay', 'void delay(unsigned long ms)', 'Pause for the given number of milliseconds.'),
  fn('delayMicroseconds', 'void delayMicroseconds(unsigned int us)', 'Pause for a short time in microseconds.'),
  fn('millis', 'unsigned long millis()', 'Milliseconds since the sketch started. Wraps after about 50 days.'),
  fn('micros', 'unsigned long micros()', 'Microseconds since startup. Wraps after about 70 minutes.'),
  fn('pulseIn', 'unsigned long pulseIn(uint8_t pin, uint8_t state, unsigned long timeout = 1000000)', 'Measure a HIGH or LOW pulse in microseconds; returns 0 on timeout.'),
  fn('pulseInLong', 'unsigned long pulseInLong(uint8_t pin, uint8_t state, unsigned long timeout = 1000000)', 'Measure a pulse using micros(); interrupts must remain enabled.'),
  fn('random', 'long random(long max) / random(long min, long max)', 'Return a pseudorandom number; the upper bound is excluded.'),
  fn('randomSeed', 'void randomSeed(unsigned long seed)', 'Set the starting seed for pseudorandom numbers.'),
  fn('map', 'long map(long x, long inMin, long inMax, long outMin, long outMax)', 'Rescale an integer value to another range. Does not clamp it.'),
  fn('constrain', 'constrain(x, minimum, maximum)', 'Limit a value to the given range. Macro: avoid arguments with side effects.'),
  fn('attachInterrupt', 'void attachInterrupt(uint8_t interrupt, void (*callback)(), int mode)', 'Use digitalPinToInterrupt(pin); Uno external interrupts are on pins 2 and 3.'),
  fn('detachInterrupt', 'void detachInterrupt(uint8_t interrupt)', 'Stop the handler for this external interrupt.'),
  fn('digitalPinToInterrupt', 'digitalPinToInterrupt(pin)', 'Convert Uno pin 2 or 3 to its external interrupt number.'),
  fn('interrupts', 'interrupts()', 'Enable interrupts.'),
  fn('noInterrupts', 'noInterrupts()', 'Disable interrupts briefly; restore them when finished.'),
  fn('tone', 'void tone(uint8_t pin, unsigned int frequency, unsigned long duration = 0)', 'Generate a square wave, optionally for a duration in milliseconds.'),
  fn('noTone', 'void noTone(uint8_t pin)', 'Stop the tone on a pin.'),
  fn('shiftOut', 'void shiftOut(uint8_t dataPin, uint8_t clockPin, uint8_t order, uint8_t value)', 'Send a byte using LSBFIRST or MSBFIRST bit order.'),
  fn('shiftIn', 'uint8_t shiftIn(uint8_t dataPin, uint8_t clockPin, uint8_t order)', 'Read a byte using a data pin and clock pin.'),
  ...['min', 'max'].map(n => fn(n, `${n}(a, b)`, `Return the ${n === 'min' ? 'smaller' : 'larger'} value. Macro: avoid side effects in arguments.`)),
  fn('abs', 'abs(x)', 'Absolute value. Macro: avoid side effects in the argument.'),
  fn('sq', 'sq(x)', 'Square a value. Macro: avoid side effects in the argument.'),
  ...['sin', 'cos', 'tan', 'sqrt'].map(n => fn(n, `double ${n}(double x)`, n === 'sqrt' ? 'Square root of a nonnegative number.' : 'Trigonometric function; angle is in radians.')),
  fn('bitRead', 'bitRead(value, bit)', 'Read a numbered bit, starting at bit 0.'),
  fn('bitWrite', 'bitWrite(value, bit, bitValue)', 'Set a bit in a variable to 0 or 1.'),
  fn('bitSet', 'bitSet(value, bit)', 'Set a bit in a variable to 1.'),
  fn('bitClear', 'bitClear(value, bit)', 'Clear a bit in a variable to 0.'),
  fn('bit', 'bit(bitNumber)', 'Return a value with only this bit set.'),
  fn('highByte', 'highByte(value)', 'Extract the second-lowest byte.'),
  fn('lowByte', 'lowByte(value)', 'Extract the lowest byte.'),
  fn('F', 'F("text")', 'Keep a string literal in flash instead of copying it into SRAM.'),
  value('Serial', 'The Uno hardware serial port. Use Serial.begin(baud) in setup().', 'variable'),
  ...Object.entries({ HIGH: 'Digital high level.', LOW: 'Digital low level.', INPUT: 'High-impedance input.', OUTPUT: 'Digital output.', INPUT_PULLUP: 'Input with the internal pull-up resistor enabled.', LED_BUILTIN: 'Uno onboard LED pin (13).', CHANGE: 'Interrupt on either edge.', RISING: 'Interrupt on a rising edge.', FALLING: 'Interrupt on a falling edge.', DEFAULT: 'Default analog reference (normally 5 V on Uno).', INTERNAL: 'Uno internal nominal 1.1 V analog reference.', EXTERNAL: 'External reference connected to AREF.', LSBFIRST: 'Least-significant bit first.', MSBFIRST: 'Most-significant bit first.', DEC: 'Print numbers in base 10.', HEX: 'Print numbers in base 16.', OCT: 'Print numbers in base 8.', BIN: 'Print numbers in base 2.', PI: 'Pi.', TWO_PI: 'Two times pi.', HALF_PI: 'Half of pi.' }).map(([n, d]) => value(n, d)),
  ...Array.from({ length: 6 }, (_, i) => value(`A${i}`, `Uno analog input pin A${i}.`)),
  ...['void', 'bool', 'boolean', 'byte', 'char', 'int', 'unsigned', 'long', 'float', 'double', 'uint8_t', 'uint16_t', 'uint32_t', 'int8_t', 'int16_t', 'int32_t', 'size_t', 'String'].map(n => value(n, `Arduino/C++ type: ${n}.`, 'type')),
  ...['const', 'static', 'volatile', 'if', 'else', 'for', 'while', 'do', 'switch', 'case', 'break', 'continue', 'return', 'class', 'struct', 'public', 'private', 'true', 'false'].map(n => value(n, `C++ keyword: ${n}.`, 'keyword')),
];

const printMethods = [
  fn('print', 'size_t print(value, format?)', 'Write a value as text; optional number base or decimal places.'),
  fn('println', 'size_t println(value?, format?)', 'Write text followed by carriage return and newline.'),
  fn('write', 'size_t write(byte) / write(buffer, length)', 'Write raw bytes.'),
];
export const serialCompletions = [
  fn('begin', 'void begin(unsigned long baud, uint8_t config = SERIAL_8N1)', 'Start hardware serial communication at the selected baud rate.'),
  fn('end', 'void end()', 'Stop hardware serial communication.'),
  fn('available', 'int available()', 'Number of bytes waiting in the receive buffer.'),
  fn('availableForWrite', 'int availableForWrite()', 'Free space in the transmit buffer.'),
  fn('read', 'int read()', 'Read the next byte; returns -1 if none is available.'),
  fn('peek', 'int peek()', 'Look at the next byte without consuming it; -1 if empty.'),
  fn('flush', 'void flush()', 'Wait until outgoing data has been transmitted.'),
  fn('setTimeout', 'void setTimeout(unsigned long milliseconds)', 'Set the timeout used by Stream parsing functions.'),
  fn('parseInt', 'long parseInt()', 'Read the next integer, waiting up to the configured timeout.'),
  fn('parseFloat', 'float parseFloat()', 'Read the next floating-point number.'),
  fn('readString', 'String readString()', 'Read characters into a String until timeout.'),
  fn('readStringUntil', 'String readStringUntil(char terminator)', 'Read until the terminator or timeout; terminator is not returned.'),
  fn('readBytes', 'size_t readBytes(char *buffer, size_t length)', 'Read into a buffer up to the requested length or timeout.'),
  ...printMethods,
];
const textDisplay = [
  fn('setCursor', 'void setCursor(column, row)', 'Move the text cursor. Character LCDs use columns/rows; graphics displays use pixels.'),
  ...printMethods,
];
const graphics = [
  ...textDisplay,
  fn('setTextSize', 'void setTextSize(uint8_t size)', 'Set the text scale.'),
  fn('setTextColor', 'void setTextColor(uint16_t color)', 'Set the text color.'),
  fn('drawPixel', 'void drawPixel(int16_t x, int16_t y, uint16_t color)', 'Draw one pixel in the framebuffer.'),
  fn('drawLine', 'void drawLine(x0, y0, x1, y1, color)', 'Draw a line in pixel coordinates.'),
  fn('fillRect', 'void fillRect(x, y, width, height, color)', 'Draw a filled rectangle.'),
  fn('fillScreen', 'void fillScreen(uint16_t color)', 'Fill the framebuffer with one color.'),
];
// A deliberately curated subset of the pinned, tested libraries' APIs.
// Headers and PASS eligibility come from the existing local library catalog.
export const libraryAPIs = {
  servo: { types: ['Servo'], methods: [fn('attach', 'uint8_t attach(int pin) / attach(int pin, int min, int max)', 'Attach a servo to a pin; optional pulse bounds are in microseconds.'), fn('write', 'void write(int angle)', 'Set a servo angle in degrees (0–180).'), fn('writeMicroseconds', 'void writeMicroseconds(int pulse)', 'Set the pulse width directly in microseconds.'), fn('read', 'int read()', 'Return the last written angle, not a physical position measurement.'), fn('attached', 'bool attached()', 'Whether this servo is attached.'), fn('detach', 'void detach()', 'Stop sending servo pulses.')] },
  wire: { types: ['TwoWire'], globals: ['Wire'], methods: [fn('begin', 'void begin() / begin(uint8_t address)', 'Join the I2C bus as controller, or as a peripheral with an address.'), fn('beginTransmission', 'void beginTransmission(uint8_t address)', 'Start buffering a transmission for an I2C address.'), fn('endTransmission', 'uint8_t endTransmission(bool stop = true)', 'Send buffered data. Returns 0 on success.'), fn('requestFrom', 'uint8_t requestFrom(uint8_t address, uint8_t count)', 'Request bytes from an I2C peripheral.'), fn('setClock', 'void setClock(uint32_t frequency)', 'Set the I2C clock frequency in hertz.'), fn('available', 'int available()', 'Number of received I2C bytes waiting.'), fn('read', 'int read()', 'Read one received I2C byte.'), fn('write', 'size_t write(value) / write(buffer, length)', 'Buffer data for an I2C transmission.')] },
  spi: { types: ['SPISettings'], globals: ['SPI'], methods: [fn('begin', 'void begin()', 'Initialize the Uno hardware SPI bus.'), fn('beginTransaction', 'void beginTransaction(SPISettings settings)', 'Configure SPI for a device transaction.'), fn('transfer', 'uint8_t transfer(uint8_t data)', 'Send and receive one byte simultaneously.'), fn('endTransaction', 'void endTransaction()', 'Finish the SPI transaction.'), fn('end', 'void end()', 'Disable the SPI bus.')] },
  eeprom: { globals: ['EEPROM'], methods: [fn('read', 'uint8_t read(int address)', 'Read a byte from EEPROM address 0–1023.'), fn('write', 'void write(int address, uint8_t value)', 'Write a byte; EEPROM has a finite write lifetime.'), fn('update', 'void update(int address, uint8_t value)', 'Write only when the stored byte differs.'), fn('get', 'T &get(int address, T &value)', 'Read a typed value into a variable.'), fn('put', 'const T &put(int address, const T &value)', 'Store a typed value, updating changed bytes only.'), fn('length', 'uint16_t length()', 'Return EEPROM capacity in bytes.')] },
  softwareserial: { types: ['SoftwareSerial'], methods: [...serialCompletions.filter(n => !['availableForWrite'].includes(n.label) && n.label !== 'begin'), fn('begin', 'void begin(long baud)', 'Start this software serial port.'), fn('listen', 'bool listen()', 'Make this the active SoftwareSerial receiver.'), fn('isListening', 'bool isListening()', 'Whether this port is the active software receiver.')] },
  liquidcrystal: { types: ['LiquidCrystal'], methods: [...textDisplay, fn('begin', 'void begin(uint8_t columns, uint8_t rows)', 'Initialize the LCD dimensions.'), fn('clear', 'void clear()', 'Clear the LCD and move the cursor home.'), fn('home', 'void home()', 'Move the LCD cursor home.'), fn('createChar', 'void createChar(uint8_t slot, uint8_t bitmap[])', 'Define one of eight custom characters.')] },
  dht: { types: ['DHT', 'DHT_Unified'], constants: ['DHT11', 'DHT22', 'DHT21'], methods: [fn('begin', 'void begin()', 'Initialize the DHT sensor.'), fn('readTemperature', 'float readTemperature(bool fahrenheit = false)', 'Read temperature; returns NaN when reading fails.'), fn('readHumidity', 'float readHumidity()', 'Read relative humidity as a percentage; NaN on failure.'), fn('computeHeatIndex', 'float computeHeatIndex(float temperature, float humidity, bool fahrenheit = true)', 'Calculate heat index from temperature and humidity.')], memberTypes: ['DHT'] },
  'unified-sensor': { types: ['Adafruit_Sensor', 'sensors_event_t', 'sensor_t'], memberTypes: ['Adafruit_Sensor'], methods: [fn('getEvent', 'bool getEvent(sensors_event_t *event)', 'Read a measurement through a concrete sensor driver.'), fn('getSensor', 'void getSensor(sensor_t *sensor)', 'Read metadata from a concrete sensor driver.')] },
  gfx: { types: ['Adafruit_GFX', 'GFXcanvas1', 'GFXcanvas8', 'GFXcanvas16'], methods: graphics },
  ssd1306: { types: ['Adafruit_SSD1306'], constants: ['SSD1306_WHITE', 'SSD1306_BLACK', 'SSD1306_INVERSE', 'SSD1306_SWITCHCAPVCC'], methods: [...graphics, fn('begin', 'bool begin(uint8_t power, uint8_t address = 0, bool reset = true, bool periphBegin = true)', 'Allocate the framebuffer and initialize the OLED; check the returned bool.'), fn('clearDisplay', 'void clearDisplay()', 'Clear the local framebuffer.'), fn('display', 'void display()', 'Send the framebuffer to the OLED.')] },
  busio: { types: ['Adafruit_I2CDevice', 'Adafruit_SPIDevice', 'Adafruit_BusIO_Register'], memberTypes: ['Adafruit_I2CDevice'], methods: [fn('begin', 'bool begin(bool addressDetect = true)', 'Initialize and optionally detect the I2C device.'), fn('read', 'bool read(uint8_t *buffer, size_t length, bool stop = true)', 'Read bytes from the device.'), fn('write', 'bool write(const uint8_t *buffer, size_t length, bool stop = true)', 'Write bytes to the device.')] },
  neopixel: { types: ['Adafruit_NeoPixel'], constants: ['NEO_GRB', 'NEO_RGB', 'NEO_RGBW', 'NEO_KHZ800', 'NEO_KHZ400'], methods: [fn('begin', 'void begin()', 'Configure the NeoPixel data pin.'), fn('show', 'void show()', 'Send the stored colors to the LED strip.'), fn('setPixelColor', 'void setPixelColor(uint16_t index, uint8_t r, uint8_t g, uint8_t b)', 'Set an LED color in memory; call show() to apply.'), fn('setBrightness', 'void setBrightness(uint8_t brightness)', 'Set brightness from 0 to 255.'), fn('clear', 'void clear()', 'Set all stored colors to off; call show() to apply.'), fn('Color', 'uint32_t Color(uint8_t r, uint8_t g, uint8_t b)', 'Pack RGB components into one color value.')] },
  newping: { types: ['NewPing'], methods: [fn('ping_cm', 'unsigned long ping_cm(unsigned int maxDistance = 0)', 'Return distance in centimeters; 0 means no echo in range.'), fn('ping', 'unsigned int ping(unsigned int maxDistance = 0)', 'Return echo time in microseconds; 0 means no echo.'), fn('ping_median', 'unsigned long ping_median(uint8_t iterations = 5, unsigned int maxDistance = 0)', 'Return the median echo time from several pings.')] },
  irremote: { globals: ['IrReceiver', 'IrSender'], methods: [fn('begin', 'void begin(uint_fast8_t receivePin, bool ledFeedback = false)', 'Start the infrared receiver.'), fn('decode', 'bool decode()', 'Return true when a received IR message is ready.'), fn('resume', 'void resume()', 'Prepare to receive the next message.'), fn('printIRResultShort', 'void printIRResultShort(Print *output)', 'Print a short received-message summary.')], memberGlobals: ['IrReceiver'] },
  keypad: { types: ['Keypad'], constants: ['NO_KEY', 'PRESSED', 'RELEASED', 'HOLD', 'IDLE'], methods: [fn('getKey', 'char getKey()', 'Return a newly pressed key or NO_KEY.'), fn('getKeys', 'bool getKeys()', 'Scan and update the list of key states.'), fn('setDebounceTime', 'void setDebounceTime(unsigned int milliseconds)', 'Set the keypad debounce interval.')] },
  accelstepper: { types: ['AccelStepper', 'MultiStepper'], memberTypes: ['AccelStepper'], methods: [fn('setMaxSpeed', 'void setMaxSpeed(float speed)', 'Set the maximum speed in steps per second.'), fn('setAcceleration', 'void setAcceleration(float acceleration)', 'Set acceleration in steps per second squared.'), fn('moveTo', 'void moveTo(long absolutePosition)', 'Set a target position in steps.'), fn('run', 'bool run()', 'Advance motion when a step is due; call frequently.'), fn('runSpeed', 'bool runSpeed()', 'Step at the configured constant speed; call frequently.'), fn('setSpeed', 'void setSpeed(float speed)', 'Set constant speed in steps per second.'), fn('distanceToGo', 'long distanceToGo()', 'Steps remaining to the target.')] },
  'liquidcrystal-i2c': { types: ['LiquidCrystal_I2C'], methods: [...textDisplay, fn('init', 'void init()', 'Initialize the pinned I2C LCD library.'), fn('backlight', 'void backlight()', 'Turn on the LCD backlight.'), fn('noBacklight', 'void noBacklight()', 'Turn off the LCD backlight.'), fn('clear', 'void clear()', 'Clear the LCD and move the cursor home.')] },
};
