import { useMemo } from 'react';
import { WorkbenchDialog } from './WorkbenchDialogs.jsx';
import { getBoard } from './boards.js';
import { inspectSketch } from './localDebug.js';
import { starterProjects } from './starterProjects.js';

export function StarterProjects({ availableExamples, onExample }) {
  return <div className="starter-projects"><p className="sidebar-note">A tested starting sketch plus the connections it expects. Each opens a new local sketch.</p>{starterProjects.filter(p=>availableExamples.includes(p.example)).map(project=><details key={project.name}><summary>{project.name}</summary><p>{project.description}</p><dl><dt>Components</dt><dd>{project.parts}</dd><dt>Connections</dt><dd>{project.connections}</dd><dt>Expected behavior</dt><dd>{project.result}</dd></dl><button onClick={()=>onExample(project.example)}>Open as new sketch</button></details>)}</div>;
}
export function DebugPanel({ onClose, sketch, boardId, baudRate, libraries, diagnostics, result, currentBuild, onJump }) {
  const files=sketch?.project?.files || (sketch ? [{name:sketch.name+'.ino',code:sketch.code}] : []);
  const notices=useMemo(()=>inspectSketch({files,boardId,baudRate,libraries,diagnostics,result,currentBuild}),[sketch,boardId,baudRate,libraries,diagnostics,result,currentBuild]);
  return <WorkbenchDialog title="Help me debug" onClose={onClose}><p className="dialog-note">Local code checks for {getBoard(boardId).shortName}. These hints do not inspect wiring, execute code, or replace the compiler. Constants, scopes and conditional compilation are only partially understood.</p>{!currentBuild && <p className="dialog-note">Verify the current source for authoritative syntax and library errors.</p>}{!notices.length && <p className="dialog-note">No obvious issue found by these limited checks. Use Verify and check your hardware connections.</p>}<div className="debug-notices">{notices.map((n,i)=><article className={n.level.toLowerCase()} key={i}><small>{n.level}</small><h3>{n.title}</h3><p>{n.text}</p>{n.line && <button onClick={()=>{onClose();onJump(n);}}>{n.file} · line {n.line}</button>}</article>)}</div></WorkbenchDialog>;
}
export function SystemCheckPanel({ onClose, onRun, running, checks, output, boardId }) {
  return <WorkbenchDialog title="System Check" onClose={onClose} busy={running}><p className="dialog-note">Run a small real compile/link for {getBoard(boardId).label}. Checks do not upload firmware, request USB permission, or change the active sketch.</p><button className="system-check-run" onClick={onRun} disabled={running}>{running?'Checking…':'Run System Check'}</button><dl className="system-check-rows">{checks.map(row=><div key={row.name}><dt>{row.name}</dt><dd data-status={row.status}>{row.status==='pass'?'✓ ':row.status==='fail'?'! ':''}{row.detail}</dd></div>)}</dl>{output && <details className="system-check-output"><summary>Technical details</summary><pre>{output}</pre></details>}<p className="dialog-note">A selected USB port is not proof of a bootloader connection. Use Test My {getBoard(boardId).family==='pb'?'ATmega328PB':getBoard(boardId).family==='nano'?'Nano':'Uno'} for a physical upload check.</p></WorkbenchDialog>;
}
export function EditorSettings({ onClose, fontSize, onFontSize, onReset, stats, sketchBytes, onGuidance, storageError }) {
  return <WorkbenchDialog title="Editor settings" onClose={onClose}><label className="font-size-setting">Font size <input type="range" min="12" max="24" step="1" value={fontSize} onChange={e=>onFontSize(e.target.value)} aria-label="Editor font size"/><output>{fontSize} px</output></label><div className="settings-actions"><button onClick={onReset}>Reset editor layout</button><button onClick={onGuidance}>Show getting started tips</button></div><p className="dialog-note">Reset restores the sidebar, output panel, console height and font size. Sketches, theme and code stay as they are. Use Ctrl/⌘+F in the editor for find and replace.</p>{storageError&&<p role="alert" className="dialog-note">{storageError}</p>}<h3 className="settings-stats-title">This session · only on this device</h3><dl className="system-check-rows"><div><dt>Compiles attempted</dt><dd>{stats.compiles}</dd></div><div><dt>Successful uploads</dt><dd>{stats.uploads}</dd></div><div><dt>Current project source</dt><dd>{sketchBytes.toLocaleString()} bytes</dd></div><div><dt>Last compile</dt><dd>{stats.lastSeconds===null?'Not run':stats.lastSeconds.toFixed(2)+' s'}</dd></div></dl></WorkbenchDialog>;
}
