// These are guides to the existing tested examples, not alternate sketch sources.
export const starterProjects = [
  { name:'Blink', example:'Blink', description:'Make the onboard LED blink.', parts:'Uno R3 or Nano V3; USB data cable.', connections:'No external wiring. The onboard LED uses D13 / LED_BUILTIN.', result:'The onboard LED alternates on and off every second.' },
  { name:'Button', example:'Button', description:'Control the onboard LED with a pushbutton.', parts:'Pushbutton and two jumper wires.', connections:'Connect the button between D2 and GND. The sketch enables INPUT_PULLUP.', result:'Pressing the button lights the onboard LED.' },
  { name:'Potentiometer', example:'Analog Input', description:'Read a knob in Serial Monitor or Plotter.', parts:'10 kΩ potentiometer and jumper wires.', connections:'Outer terminals to 5V and GND; middle terminal (wiper) to A0.', result:'Readings at 9600 baud change from about 0 to 1023 as the knob turns.' },
  { name:'Servo Sweep', example:'Servo sweep', description:'Sweep a hobby servo through its range.', parts:'Hobby servo and an appropriate regulated supply.', connections:'Signal to D9. Power the servo according to its specifications; join its supply GND to board GND. Do not power a motor from an I/O pin.', result:'The servo sweeps between 0° and 180°; keep its arm clear.' },
  { name:'Ultrasonic Distance', example:'Ultrasonic', description:'Measure range with an HC-SR04.', parts:'HC-SR04 and four jumper wires.', connections:'VCC to 5V, GND to GND, TRIG to D9, ECHO to D10.', result:'Serial Monitor at 9600 baud shows distance in cm. A timeout/no echo produces zero.' },
  { name:'Temperature / Humidity', example:'DHT temperature-humidity', description:'Read a DHT22 sensor.', parts:'DHT22 module (or bare sensor with data pull-up).', connections:'Data to D2, GND to GND, power per module specifications. A bare DHT22 needs a 4.7–10 kΩ data pull-up. Change DHT22 to DHT11 in code if using that model.', result:'Temperature in °C and relative humidity appear at 9600 baud every two seconds.' },
  { name:'OLED Hello World', example:'OLED Hello World', description:'Draw text and a rectangle on a small OLED.', parts:'128×64 SSD1306 I2C OLED compatible with 5V logic.', connections:'SDA to A4, SCL to A5, common GND, power per module specifications. Example address: 0x3C; use the I2C scanner to confirm.', result:'The display shows “Hello, maker!” and a rectangle. The framebuffer needs about 1 KB of RAM.' },
  { name:'NeoPixel', example:'NeoPixel', description:'Move a colored pixel along eight LEDs.', parts:'Eight 5V WS2812-compatible LEDs and appropriate power supply.', connections:'D6 through a 300–500 Ω series resistor to DIN; join board and LED supply GND. Power LEDs from a supply suitable for the strip; do not power them from an I/O pin.', result:'A dim cyan pixel moves through eight LEDs. Match the pixel count and color order to your strip.' },
];
