import HelpPage, { HelpLinks, helpTopics } from './HelpPages.jsx';
import { ArrowRight, ArrowUpRight, Code2, Cpu, Usb, Terminal, FolderOpen, Sparkles, BookOpen, Activity, HardDrive, Download, Check, ChevronRight, CircuitBoard, Zap, LockKeyhole } from 'lucide-react';
import { examplePath } from './routes.js';

export const projects = [
  { name: 'Blink', sketch: 'Blink', description: 'Make your first connection between code and the real world.', level: 'Beginner', parts: 'Uno R3 · USB cable', kind: 'led', color: 'blue' },
  { name: 'Reaction Game', sketch: 'Reaction Game', description: 'Light on. Button down. How quick is your reaction?', level: 'Beginner', parts: 'Uno · button · USB cable', kind: 'button', color: 'orange' },
  { name: 'Ultrasonic Parking Sensor', sketch: 'Parking Sensor', description: 'Measure the gap and turn distance into sound.', level: 'Intermediate', parts: 'Uno · HC-SR04 · buzzer', kind: 'sensor', color: 'cyan' },
  { name: 'Servo Control', sketch: 'Servo sweep', description: 'Sweep a servo arm with precise position commands.', level: 'Beginner', parts: 'Uno · hobby servo · suitable power', kind: 'servo', color: 'purple' },
  { name: 'Automatic Door', sketch: 'Automatic Door', description: 'Combine distance sensing with a small servo model.', level: 'Intermediate', parts: 'Uno · HC-SR04 · servo · suitable power', kind: 'servo', color: 'green' },
  { name: 'OLED Display', sketch: 'OLED Hello World', description: 'Give your project its own small screen.', level: 'Intermediate', parts: 'Uno · SSD1306 I²C OLED', kind: 'display', color: 'blue' },
  { name: 'DHT Weather Station', sketch: 'DHT temperature-humidity', description: 'Read temperature and humidity in Serial Monitor.', level: 'Intermediate', parts: 'Uno · DHT22 · pull-up resistor', kind: 'sensor', color: 'orange' },
  { name: 'Motion Alarm', sketch: 'Motion Alarm', description: 'Read a motion sensor and trigger a simple alert.', level: 'Beginner', parts: 'Uno · PIR sensor · buzzer · LED', kind: 'sensor', color: 'purple' },
];

export const features = [
  [Code2, 'blue', 'A real C++ workspace', 'A focused Arduino editor with syntax highlighting, local autocomplete and clickable compiler diagnostics.'],
  [Cpu, 'green', 'Compiled on your Chromebook', 'AVR-GCC runs through WebAssembly in a Web Worker. Your current code becomes real Intel HEX firmware.'],
  [Usb, 'orange', 'Meet your physical board', 'Connect an Uno R3 or Nano V3 through Chrome Web Serial. Upload with STK500v1 and verify the flash by reading it back.'],
  [Terminal, 'cyan', 'See what your circuit is saying', 'Send and receive data in Serial Monitor, or graph numerical sensor readings in the lightweight Serial Plotter.'],
  [BookOpen, 'purple', 'Libraries, already there', 'Use the curated, compile-tested library collection, including Servo, Wire, DHT and Adafruit display libraries.'],
  [FolderOpen, 'blue', 'Room for every experiment', 'Multiple sketches and editor tabs, independent autosave, import/export .ino and Export All as a ZIP.'],
];

export const steps = [
  ['01', Code2, 'blue', 'Write code', 'Start with an example or write your own Arduino C++. Autocomplete helps with names and function signatures.'],
  ['02', Cpu, 'purple', 'Compile locally', 'AVR-GCC WebAssembly compiles your sketch and its required libraries in a browser worker.'],
  ['03', HardDrive, 'orange', 'Generate firmware', 'Compiled objects are linked for ATmega328P and converted into genuine Intel HEX.'],
  ['04', Usb, 'cyan', 'Connect Uno', 'Plug in an Uno R3 and select its serial port in Chrome’s device chooser.'],
  ['05', Download, 'green', 'Upload', 'The Uno bootloader receives the firmware through STK500v1. Circuitera reads flash back to verify it.'],
  ['06', Zap, 'yellow', 'Run', 'Your Uno runs the program. Use Serial Monitor or Serial Plotter to follow its output.'],
];

export function Brand() {
  return <a className="site-brand" href="/" data-route aria-label="Circuitera home"><img src="/brand/circuitera-icon.svg" alt="" width="29" height="29" /><span>Circuitera<span className="brand-period">.</span></span></a>;
}

export function SiteHeader({ path }) {
  return <header className="site-header"><div className="site-nav-wrap"><Brand /><nav aria-label="Main navigation">{[['/about', 'About'], ['/features', 'Features'], ['/how-it-works', 'How It Works'], ['/examples', 'Examples'], ['/getting-started', 'Help'], ['/', 'IDE']].map(([url, name]) => <a key={url} href={url} data-route aria-current={path === url ? 'page' : undefined}>{name}{name === 'IDE' && <ArrowUpRight size={13} />}</a>)}</nav></div></header>;
}

export function SiteFooter() {
  return <footer className="site-footer"><div><Brand /><span>Build hardware from your browser.</span><a href="/features" data-route>Explore the workspace <ArrowUpRight size={14} /></a></div><p>Circuitera is an independent project and is not affiliated with Arduino. Arduino is a trademark of Arduino SA.</p><HelpLinks/><p className="site-privacy-note">No account required. Sketches stay in this browser’s local storage. No advertising or tracking analytics.</p></footer>;
}

function WorkbenchIllustration() {
  return <div className="hero-workbench" role="img" aria-label="Illustration of Arduino C++ becoming firmware and travelling from a browser to an Uno board.">
    <div className="bench-topline"><span className="tiny-node green" /> BROWSER → HARDWARE <span className="bench-index">FIG. 01</span></div>
    <div className="bench-code"><div className="bench-codebar"><Code2 size={14} /><span>first_blink.ino</span><span className="bench-local">LOCAL C++</span></div><pre><span className="sample-comment">// a little code. a real circuit.</span>{'\n'}<span className="sample-type">void</span> <span className="sample-function">setup</span>() {'{'}{'\n'}{'  '}<span className="sample-function">pinMode</span>(LED_BUILTIN, <span className="sample-keyword">OUTPUT</span>);{'\n'}{'}'}{'\n\n'}<span className="sample-type">void</span> <span className="sample-function">loop</span>() {'{'}{'\n'}{'  '}<span className="sample-function">digitalWrite</span>(LED_BUILTIN, <span className="sample-keyword">HIGH</span>);{'\n'}{'  '}<span className="sample-function">delay</span>(<span className="sample-number">1000</span>);{'\n'}{'}'}</pre></div>
    <div className="bench-transfer"><span><Cpu size={15} /> AVR-GCC</span><span className="signal-track"><i /></span><span className="hex-label">.HEX</span><span className="signal-track second"><i /></span><span><Usb size={15} /> USB</span></div>
    <div className="bench-board"><svg viewBox="0 0 390 150" aria-hidden="true"><rect x="28" y="10" width="334" height="128" rx="9" fill="#eef7f3" stroke="#277d62" strokeWidth="1.5" /><path d="M115 37H165V60M244 88H308V110M119 112H172V93M243 48H302V35" fill="none" stroke="#abd6c3" strokeWidth="2" /><rect x="9" y="49" width="47" height="49" rx="4" fill="#fff" stroke="#647b77" strokeWidth="2" /><rect x="13" y="56" width="29" height="33" rx="2" fill="#d6e5e1" /><rect x="160" y="46" width="92" height="54" rx="3" fill="#243633" /><text x="206" y="75" textAnchor="middle" fontSize="10" fontFamily="monospace" fill="#d8ede4">ATmega328P</text>{[0,1,2,3,4,5,6,7,8,9,10,11].map(n => <g key={n}><rect x={92+n*19} y="18" width="9" height="9" rx="1" fill="#344b43" /><rect x={92+n*19} y="119" width="9" height="9" rx="1" fill="#344b43" /></g>)}{[0,1,2,3,4,5,6].map(n => <g key={n}><path d={`M${170+n*12} 39v7m0 54v7`} stroke="#6c8980" strokeWidth="3" /></g>)}<circle cx="76" cy="29" r="5" fill="#faf8f3" stroke="#648879" /><circle cx="340" cy="114" r="5" fill="#faf8f3" stroke="#648879" /><circle className="board-led" cx="310" cy="68" r="5" fill="#efa52c" /><text x="297" y="88" fontSize="8" fontFamily="monospace" fill="#3b6054">LED 13</text><text x="76" y="87" fontSize="13" fontWeight="700" fontFamily="monospace" fill="#277d62">UNO R3</text></svg><div><span>16 MHz</span><span>ATmega328P</span><span>REAL HARDWARE</span></div></div>
    <div className="bench-footnote"><span className="tiny-node blue" /> Your code stays on your computer.</div>
  </div>;
}

function FeatureGrid({ compact = false }) {
  return <div className="feature-grid">{features.slice(0, compact ? 3 : 6).map(([Icon, color, name, text], i) => <article key={name} className={`feature-item accent-${color}`}><span className="feature-number">0{i + 1}</span><Icon size={24} strokeWidth={1.7} /><h3>{name}</h3><p>{text}</p></article>)}</div>;
}

export function AboutPage() {
  return <><section className="site-hero"><div className="hero-copy"><p className="eyebrow"><span className="tiny-node green" /> THE BROWSER IS YOUR WORKBENCH</p><h1>Circuitera<span className="brand-period">.</span></h1><h2>Build hardware<br />from your browser.</h2><p className="hero-description">Write, compile, and upload Arduino Uno or Nano code directly from Chrome. No desktop IDE, Terminal, Linux, or extension required.</p><div className="hero-actions"><a className="site-button" href="/" data-route>Open IDE <ArrowRight size={18} /></a><a className="site-button secondary" href="/how-it-works" data-route>Learn How It Works <ChevronRight size={17} /></a></div><div className="hero-spec"><span>UNO R3 + NANO V3</span><i /><span>CHROME + WEB SERIAL</span><i /><span>LOCAL COMPILATION</span></div></div><WorkbenchIllustration /></section>
    <div className="site-ribbon"><span><Code2 size={18} /> Write real C++</span><span><Cpu size={18} /> Compile on your device</span><span><Usb size={18} /> Upload to a real Uno</span><span><LockKeyhole size={17} /> Keep your sketches local</span></div>
    <section className="site-section"><div className="section-heading"><div><p className="eyebrow orange-text">SMALL SETUP. REAL POSSIBILITIES.</p><h2>Less setup. More making.</h2></div><a href="/features" data-route>See all features <ArrowUpRight size={17} /></a></div><FeatureGrid compact /></section>
    <section className="site-section project-preview"><div className="section-heading"><div><p className="eyebrow purple-text">START WITH A SPARK</p><h2>From a blinking LED to your next idea.</h2></div><a href="/examples" data-route>Explore examples <ArrowUpRight size={17} /></a></div><div className="starter-links">{projects.filter((_,i) => [0,3,5].includes(i)).map(project => <a key={project.name} href={examplePath(project.sketch)} data-route className={`accent-${project.color}`}><ProjectGraphic kind={project.kind} /><div><span>{project.level}</span><h3>{project.name}</h3></div><ArrowUpRight size={20} /></a>)}</div></section>
    <section className="site-section about-notes"><div><p className="eyebrow cyan-text">A WORKBENCH THAT FITS IN A TAB</p><h2>Built for curious minds.<br />Ready for real engineering.</h2></div><div><p>Circuitera is a fast, browser-based development environment for Arduino Uno R3 and Nano V3. It brings a real compiler and physical board uploading to Chrome on a Chromebook.</p><p>Open Circuitera and start coding immediately. Code, firmware and multiple sketches stay local to this browser. No signup, email or password required.</p><a href="/" data-route className="text-action">Let’s open the workbench <ArrowRight size={17} /></a></div></section></>;
}

export function FeaturesPage() {
  return <><PageIntro label="THE TOOLKIT" title="Everything between an idea and a working circuit." description="A focused Arduino web IDE, with the tools you need to write, debug and build. No desktop installation." /><section className="site-section first-section"><FeatureGrid /></section><section className="site-section detail-band"><div><span className="eyebrow purple-text">PREINSTALLED, NOT COMPLICATED</span><h2>Start with #include.</h2><p>Servo, Wire, SPI, EEPROM, SoftwareSerial, LiquidCrystal, DHT, Adafruit libraries, NewPing, IRremote, Keypad, AccelStepper and LiquidCrystal_I2C are part of the curated collection.</p><p>Each supported library has passed real compile-and-link tests. The IDE shows versions, dependencies, examples and real compiler errors.</p></div><div className="include-sample"><code><span className="sample-type">#include</span> &lt;Servo.h&gt;<br /><span className="sample-type">Servo</span> myServo;<br /><br /><span className="sample-comment">// ready when you are</span></code><span><Check size={15} /> Preinstalled libraries</span></div></section><section className="site-section small-facts"><div><Sparkles /><h3>Helpful, entirely local</h3><p>Autocomplete suggests Arduino functions, constants, Serial methods and symbols in your current sketch. No remote AI service.</p></div><div><Activity /><h3>Monitor and plot</h3><p>Choose a baud rate, send a command, add timestamps or watch changing numerical data on a live plot.</p></div><div><HardDrive /><h3>Your browser, your files</h3><p>IndexedDB restores sketches and tabs after refresh. Export files to keep a separate backup or move between devices.</p></div></section><OpenWorkbench /></>;
}

export function HowPage() {
  return <><PageIntro label="FROM SOURCE TO SIGNAL" title="A direct path from code to your Uno." description="The compiler runs in your browser. The finished firmware goes straight to the board you connect." /><section className="site-section first-section"><div className="how-steps">{steps.map(([number, Icon, color, title, text]) => <article className={`how-step accent-${color}`} key={number}><div className="step-rail"><span>{number}</span></div><div><Icon size={24} /><h2>{title}</h2><p>{text}</p></div><span className="flow-pulse" aria-hidden="true" /></article>)}</div></section><section className="site-section setup-note"><CircuitBoard size={31} /><div><h2>Bring your board. Open Chrome.</h2><p>Use an Arduino Uno R3 or classic Nano V3 / ATmega328P and a USB data cable. Choose the matching board and bootloader before compiling or uploading. Chrome must allow Web Serial for this site. Device selection happens only when you click Connect or Upload.</p><p className="school-note">USB serial access is unavailable on this Chromebook? Ask your teacher or school IT administrator to allow serial-device access for this site.</p></div></section><OpenWorkbench /></>;
}

function ProjectGraphic({ kind }) {
  return <svg className="project-graphic" viewBox="0 0 120 78" fill="none" aria-hidden="true"><path d="M9 61H31V49M111 20H92V32" stroke="currentColor" strokeOpacity=".22" strokeWidth="2" /><circle cx="9" cy="61" r="3" fill="currentColor" opacity=".35" /><circle cx="111" cy="20" r="3" fill="currentColor" opacity=".35" />{kind === 'led' ? <><path d="M46 51V31a14 14 0 0128 0v20z" stroke="currentColor" strokeWidth="3" /><path d="M43 51h34M53 53v19m14-19v14M60 5V0M37 13l-6-6m52 6l6-6" stroke="currentColor" strokeWidth="2" /><path d="M52 31v8" stroke="currentColor" strokeWidth="3" strokeLinecap="round" /></> : kind === 'servo' ? <><rect x="33" y="28" width="58" height="37" rx="3" stroke="currentColor" strokeWidth="2" /><path d="M60 30V18m0 0H32m28 0h28" stroke="currentColor" strokeWidth="6" strokeLinecap="round" /><circle cx="60" cy="18" r="7" fill="currentColor" /><path d="M48 66v9m10-9v9m10-9v9" stroke="currentColor" strokeWidth="2" /></> : kind === 'display' ? <><rect x="27" y="14" width="72" height="47" rx="3" stroke="currentColor" strokeWidth="2" /><rect x="32" y="19" width="62" height="36" rx="1" fill="currentColor" opacity=".1" /><path d="M41 30h34M41 37h22m-22 7h45M43 64v9m12-9v9m12-9v9m12-9v9" stroke="currentColor" strokeWidth="2" /></> : kind === 'button' ? <><rect x="37" y="15" width="48" height="47" rx="3" stroke="currentColor" strokeWidth="2" /><circle cx="61" cy="39" r="13" fill="currentColor" opacity=".2" /><circle cx="61" cy="39" r="9" stroke="currentColor" strokeWidth="2" /><path d="M38 26H28m10 25H28m57-25h10M85 51h10" stroke="currentColor" strokeWidth="3" /></> : <><rect x="22" y="20" width="82" height="37" rx="3" stroke="currentColor" strokeWidth="2" /><circle cx="43" cy="38" r="13" stroke="currentColor" strokeWidth="2" /><circle cx="82" cy="38" r="13" stroke="currentColor" strokeWidth="2" /><circle cx="43" cy="38" r="8" fill="currentColor" opacity=".17" /><circle cx="82" cy="38" r="8" fill="currentColor" opacity=".17" /><path d="M49 59v12m9-12v12m9-12v12m9-12v12" stroke="currentColor" strokeWidth="2" /></>}</svg>;
}

export function ExamplesPage() {
  return <><PageIntro label="PICK A STARTING POINT" title="Small projects. Big ‘it works’ moments." description="Real sketches from the Circuitera example collection. Choose a project and open a fresh sketch without replacing your work." /><section className="site-section first-section"><div className="project-grid">{projects.map(project => <article className={`project-card accent-${project.color}`} key={project.name}><div className="project-art"><ProjectGraphic kind={project.kind} /><span>{project.level}</span></div><div className="project-content"><h2>{project.name}</h2><p>{project.description}</p><div className="project-parts"><span>ON YOUR BENCH</span>{project.parts}</div><a href={examplePath(project.sketch)} data-route>Open in IDE <ArrowUpRight size={17} /></a></div></article>)}</div><p className="examples-note">Every listed sketch is included in the IDE and compile-tested for the Uno R3. Follow the pin assignments and hardware notes in the code; check your component’s power requirements.</p></section></>;
}

export function PageIntro({ label, title, description }) { return <section className="page-intro"><p className="eyebrow blue-text">{label}</p><h1>{title}</h1><p>{description}</p></section>; }
function OpenWorkbench() { return <section className="site-section open-workbench"><div><span className="tiny-node green" /><h2>Your next circuit starts here.</h2></div><a href="/" className="site-button" data-route>Open IDE <ArrowRight size={17} /></a></section>; }
export function PublicPage({ path, catalog }) {
  if (helpTopics.some(([url])=>url===path) && path !== '/how-it-works') return <HelpPage path={path} catalog={catalog}/>;
  return path === '/features' ? <FeaturesPage /> : path === '/how-it-works' ? <HowPage /> : path === '/examples' ? <ExamplesPage /> : <AboutPage />;
}
